modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/TerraForged/PreGenForge/issues"
[[mods]]
    displayName="PreGenForge"
    modId="pregenforge"
    version="@version@"
    authors="dags"
    description="A chunk pre-generator"